server:
  port: 8084

spring:
  application:
    name: shop-service
  datasource:
    #    url: jdbc:postgresql://localhost/event_service
    url: jdbc:postgresql://localhost:5433/shop
    username: postgres
    password: postgres
  #    driver-class-name: org.postgresql.Driver
  #    sql-script-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

token:
  expiration: 600000000
  secret: secret

  refresh:
    expiration: 6000000000

file:
  upload:
    dir: 'C:\'